"use strict";

const js = require("@eslint/js");
const globals = require("globals");

module.exports = [
    {
        ignores: ["ext_lib/**", ".claude/**", "eslint.config.js", ".eslintrc.js"]
    },
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "script",
            globals: {
                ...globals.browser,
                ...globals.worker,
                ...globals.webextensions,
                activateTab: "readonly",
                applyTheme: "readonly",
                areSameArrays: "readonly",
                buildDuplicateTabRows: "readonly",
                buildGroupedDuplicateTabRows: "readonly",
                changeAutoCloseOptionState: "readonly",
                closeDuplicateTabs: "readonly",
                debounce: "readonly",
                environment: "writable",
                focusTab: "readonly",
                getActiveTabId: "readonly",
                getActiveWindowId: "readonly",
                getElement: "readonly",
                getElements: "readonly",
                getHighlightBounds: "readonly",
                getMatchingURL: "readonly",
                getMatchPatternURL: "readonly",
                getStoredOptions: "readonly",
                getTab: "readonly",
                getTabs: "readonly",
                getWindows: "readonly",
                highlightBottomScrollShadow: "readonly",
                initializeOptions: "readonly",
                isBlankURL: "readonly",
                isChromeURL: "readonly",
                isPanelOptionOpen: "readonly",
                isTabComplete: "readonly",
                localizePopup: "readonly",
                moveTab: "readonly",
                options: "readonly",
                refreshDuplicateTabsInfo: "readonly",
                resizeDuplicateTabsPanel: "readonly",
                setDuplicateTableButtonsEnabled: "readonly",
                updatePauseButton: "readonly",
                refreshGlobalDuplicateTabsInfo: "readonly",
                reloadTab: "readonly",
                removeTab: "readonly",
                requestCloseDuplicateTabs: "readonly",
                requestDuplicateTabsFromPanel: "readonly",
                requestGetDuplicateTabs: "readonly",
                removeStoredOptions: "readonly",
                saveOption: "readonly",
                saveStoredOptions: "readonly",
                searchForDuplicateTabsToClose: "readonly",
                sendMessage: "readonly",
                setBadge: "readonly",
                setBadgeIcon: "readonly",
                setStoredOption: "readonly",
                setTabBadgeBackgroundColor: "readonly",
                setTabBadgeText: "readonly",
                setWindowBadgeBackgroundColor: "readonly",
                setWindowBadgeText: "readonly",
                tabsInfo: "readonly",
                updateBadgeStyle: "readonly",
                updateBadgesValue: "readonly",
                updateGroupButton: "readonly",
                updateHideWhitelistedButton: "readonly",
                updateIgnorePathPartDependents: "readonly",
                wait: "readonly",
                debouncedBatchClose: "readonly",
                dispatchTabCompletion: "readonly",
                dtcLog: "readonly",
                handleRemainingTab: "readonly",
                registerWithTST: "readonly",
                setPausedBadge: "readonly",
                startupBurst: "readonly",
                _savingLocally: "writable",
                _seededTabIds: "writable",
                activeWindowId: "writable",
                clearDtcLogs: "readonly",
                defaultOptions: "readonly",
                expandTSTTabIfCollapsed: "readonly",
                getDtcLogs: "readonly",
                getDtcUrlMap: "readonly",
                getNbDuplicateTabs: "readonly",
                highlightBottomScrollShadowTimer: "writable",
                isHttps: "readonly",
                isUrlWhiteListed: "readonly",
                isValidURL: "readonly",
                monitoringPaused: "writable",
                setOptions: "readonly",
                tabExists: "readonly",
                titleSimilarity: "readonly",
                toggleMonitorPause: "readonly",
                _pendingTriggerTabId: "writable",
                registerDuplicateTableClickHandler: "readonly",
                updatePrioritizeActiveWindowState: "readonly"
            }
        },
        rules: {
            "accessor-pairs": "error",
            "array-bracket-newline": "error",
            "array-bracket-spacing": ["error", "never"],
            "array-callback-return": "error",
            "array-element-newline": "off",
            "arrow-body-style": "error",
            "arrow-parens": "off",
            "arrow-spacing": ["error", { "after": true, "before": true }],
            "block-scoped-var": "error",
            "block-spacing": "error",
            "camelcase": ["error", { "properties": "never" }],
            "class-methods-use-this": "error",
            "comma-dangle": "error",
            "comma-spacing": ["error", { "after": true, "before": false }],
            "comma-style": ["error", "last"],
            // "complexity": "error",
            "computed-property-spacing": ["error", "never"],
            "consistent-return": "off",
            "consistent-this": "error",
            "curly": "off",
            "default-param-last": "error",
            "dot-location": "error",
            "dot-notation": ["error", { "allowKeywords": true }],
            "eol-last": ["error", "never"],
            "eqeqeq": "off",
            "func-call-spacing": "error",
            "func-name-matching": "error",
            "func-style": ["error", "expression"],
            "function-paren-newline": "error",
            "generator-star-spacing": "error",
            "grouped-accessor-pairs": "error",
            "id-denylist": "error",
            "id-length": "off",
            "id-match": "error",
            "implicit-arrow-linebreak": ["error", "beside"],
            "init-declarations": "error",
            "jsx-quotes": "error",
            "key-spacing": "error",
            "keyword-spacing": ["error", { "after": true, "before": true }],
            "line-comment-position": "error",
            "linebreak-style": ["error", "windows"],
            "lines-around-comment": "error",
            "lines-between-class-members": "error",
            "max-depth": "error",
            "max-len": "off",
            "max-lines": "off",
            "max-lines-per-function": "off",
            "max-nested-callbacks": "error",
            "max-statements": "off",
            "max-statements-per-line": "error",
            "new-cap": "error",
            "new-parens": "error",
            "no-alert": "error",
            "no-array-constructor": "error",
            "no-await-in-loop": "off",
            "no-bitwise": "error",
            "no-caller": "error",
            "no-confusing-arrow": "error",
            "no-console": "off",
            "no-constructor-return": "error",
            "no-continue": "off",
            "no-div-regex": "error",
            "no-dupe-else-if": "error",
            "no-duplicate-imports": "error",
            "no-else-return": "error",
            "no-empty-function": "error",
            "no-eq-null": "error",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-label": "error",
            "no-extra-parens": "off",
            "no-floating-decimal": "error",
            "no-implicit-coercion": "error",
            "no-implicit-globals": "error",
            "no-implied-eval": "error",
            "no-import-assign": "error",
            "no-inline-comments": "error",
            "no-iterator": "error",
            "no-label-var": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-loop-func": "error",
            "no-magic-numbers": "off",
            "no-mixed-operators": "error",
            "no-multi-assign": "error",
            "no-multi-spaces": "error",
            "no-multi-str": "error",
            "no-multiple-empty-lines": "error",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-object": "error",
            "no-new-wrappers": "error",
            "no-octal-escape": "error",
            "no-param-reassign": "error",
            "no-plusplus": "error",
            "no-proto": "error",
            "no-redeclare": ["error", { "builtinGlobals": false }],
            "no-restricted-globals": "error",
            "no-restricted-imports": "error",
            "no-restricted-properties": "error",
            "no-restricted-syntax": "error",
            "no-return-assign": "error",
            "no-script-url": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-setter-return": "error",
            "no-shadow": "error",
            "no-template-curly-in-string": "error",
            "no-ternary": "off",
            "no-throw-literal": "error",
            "no-undef-init": "error",
            "no-undefined": "error",
            "no-unmodified-loop-condition": "error",
            "no-unneeded-ternary": "error",
            "no-unused-expressions": ["error", { "allowTernary": true }],
            "no-unused-vars": ["error", { "vars": "local" }],
            "no-use-before-define": "off",
            "no-useless-call": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "error",
            "no-void": "error",
            "no-warning-comments": "error",
            "no-whitespace-before-property": "error",
            "nonblock-statement-body-position": "error",
            "object-curly-newline": "error",
            "object-curly-spacing": ["error", "always"],
            "object-shorthand": "error",
            "one-var": "off",
            "one-var-declaration-per-line": "error",
            "operator-assignment": ["error", "always"],
            "operator-linebreak": "error",
            "padded-blocks": "off",
            "padding-line-between-statements": "error",
            "prefer-arrow-callback": "error",
            "prefer-const": "error",
            "prefer-destructuring": "off",
            "prefer-exponentiation-operator": "error",
            "prefer-numeric-literals": "error",
            "prefer-promise-reject-errors": ["error", { "allowEmptyReject": true }],
            "prefer-regex-literals": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "error",
            "quote-props": "off",
            "quotes": ["error", "double"],
            "radix": "error",
            "require-await": "error",
            "require-unicode-regexp": "off",
            "rest-spread-spacing": ["error", "never"],
            "semi": "error",
            "semi-spacing": "error",
            "semi-style": ["error", "last"],
            "sort-imports": "error",
            "sort-keys": "off",
            "sort-vars": "error",
            "space-before-blocks": "error",
            "space-in-parens": ["error", "never"],
            "space-infix-ops": "error",
            "space-unary-ops": "error",
            "spaced-comment": ["error", "always"],
            "strict": "off",
            "switch-colon-spacing": "error",
            "symbol-description": "error",
            "template-curly-spacing": "error",
            "template-tag-spacing": "error",
            "unicode-bom": ["error", "never"],
            "vars-on-top": "error",
            "wrap-iife": "error",
            "wrap-regex": "error",
            "yield-star-spacing": "error",
            "yoda": ["error", "never"]
        }
    }
];
